### ISSUE TITLE
Didn't work after deployed on heroku

### ISSUE THREAD

**Issue by titu3e** [lostb053/anibot#14]
Sorry

**Comment by F36** [comment]
@titu3e ಠ_ಠ

**Comment by F36** [comment]
@titu3e Logs, errors, provide something that describes the error instead of copy pasting GitHub open issue instructions

**Comment by titu3e** [comment]
> @titu3e Logs, errors, provide something that describes the error instead of copy pasting GitHub open issue instructions

Well I didn't get any log errors or such that but after messeging it on telegram it isnt responding

**Comment by lostb053** [comment]
Mind if i ask you
Were you able to deploy bot?
If not, would you please contact us so that we can help you in telegram

**Comment by F36** [comment]
@zYxDevs ───────────────▄▄───▐█
───▄▄▄───▄██▄──█▀───█─▄
─▄██▀█▌─██▄▄──▐█▀▄─▐█▀
▐█▀▀▌───▄▀▌─▌─█─▌──▌─▌
▌▀▄─▐──▀▄─▐▄─▐▄▐▄─▐▄─▐▄

**Comment by lostb053** [comment]
Guy edited initiating comment
And no response as I asked him stuff
Guess I should close it here
