### ISSUE TITLE
Invalid parse mode "markdown"

### ISSUE THREAD

**Issue by zYxDevs** [lostb053/anibot#28]
I found this when run /term

https://nekobin.com/sokumecate

**Comment by ALiwoto** [comment]
@zYxDevs @lucky9727 didn't you convert all of these pyro strings to enums after upgrading to pyro 2.0?

**Comment by ALiwoto** [comment]
@ALiwoto Then I guess they have a fork of their own, which isn't up-to-date with latest one

Anyway, it's their issue

**Comment by ALiwoto** [comment]
This dumb bot tagged my own account with my own account....

**Comment by lostb053** [comment]
LMFAO
Anyways, my code's updated and works well
